export const JOBS=[{title:'Emergency rubber chicken',detail:'Comedy club · LEFT curb',side:-1,pay:35,recipient:'COMEDY CLUB',cargo:'RUBBER CHICKEN'},{title:'Soup. No lid. Good luck.',detail:'Noodle shop · RIGHT curb',side:1,pay:45,recipient:'NOODLE SHOP',cargo:'HOT SOUP'},{title:'Lunch for the mayor’s pigeon',detail:'City hall · LEFT curb',side:-1,pay:40,recipient:'CITY HALL',cargo:'PIGEON LUNCH'},{title:'One extremely urgent sock',detail:'Laundromat · RIGHT curb',side:1,pay:30,recipient:'LAUNDROMAT',cargo:'LONE SOCK'},{title:'Birthday cake for a cactus',detail:'Plant shop · RIGHT curb',side:1,pay:50,recipient:'PLANT SHOP',cargo:'CACTUS CAKE'}];
export function createShift(choice=0){return {phase:'play',endReason:null,streak:0,bestStreak:0,streakBonus:0,specialBonus:0,lastDodge:-100,condition:1,stolen:null,thefts:0,recovered:0,dogStole:false,route:'main',routeEnd:0,forkAt:480,forkOpen:false,dogReadyAt:0,routeBonus:0,shortcuts:0,toys:0,toyCool:0,dogDistract:0,nearMisses:0,tips:0,comboTime:0,comboKinds:[],comboBonus:0,dogIntro:0,time:60,elapsed:0,distance:0,speed:30,lane:0,targetLane:0,jump:0,jumpDuration:.85,jumpHeight:65,trickType:0,grindEnd:0,grindLane:0,grindPaid:0,landing:0,jumpCool:0,deliverCool:0,obstacles:[{z:230,lane:0,type:"toy",hit:false},{z:340,lane:0,type:"ramp",hit:false},{z:530,lane:1,type:"rail",length:140,hit:false}],spawnAt:400,job:{...JOBS[choice],at:650},cash:0,jobs:0,tricks:0,bestCombo:0,combo:0,crashes:0,hazard:0,toast:'Clocked in. Stay employed.',toastTime:2,chase:false,dogLane:0,dogTurn:0,dogEscapeHold:0,dogGap:10,dogEvents:0,stun:0,effects:[],event:null,ambulance:0};}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function message(s,text){s.toast=text;s.toastTime=2;}
function nextJob(s){const j=JOBS[(s.jobs+s.crashes+Math.floor(s.elapsed/10))%JOBS.length];s.condition=1;s.job={...j,at:s.distance+(s.route==='shortcut'?450:s.route==='safe'?700:620)};}
export const TRICKS=['OLLIE','KICKFLIP','360 SPIN','DOUBLE KICKFLIP','720 SPIN','METHOD GRAB','INDY GRAB','MELON GRAB','NOSE GRAB'];
function link(s,kind){if(s.comboTime<=0){s.combo=0;s.comboKinds=[];}s.combo++;s.comboTime=6;if(!s.comboKinds.includes(kind))s.comboKinds.push(kind);s.bestCombo=Math.max(s.bestCombo,s.combo);}
export function neighborhood(s){return Math.floor(s.distance/1500)%3;}
function launch(s,random,big=false){s.grindEnd=0;s.trickType=(big?3:0)+Math.min(big?5:2,Math.floor(random()*(big?6:3)));s.jumpDuration=big?1.8:.85;s.jumpHeight=big?135:65;s.jump=s.jumpDuration;s.jumpCool=s.jumpDuration+.3;s.tricks++;link(s,big?'ramp':'trick');const tip=[2,4,6,18,24,30,22,26,32][s.trickType]+(s.combo%3===0?2:0);s.cash+=tip;if(s.chase)s.dogGap+=big?3:1.25;message(s,(big?'BIG AIR! ':'')+TRICKS[s.trickType]+'! +$'+tip);s.event='jump';}
export function update(s,input,dt,random=Math.random){dt=clamp(dt,0,.05);s.toastTime=Math.max(0,s.toastTime-dt);s.effects=s.effects.filter(e=>e.until>s.elapsed);if(s.phase==='ambulance'){s.ambulance+=dt;if(s.ambulance>(s.endReason==='car'?7.5:5.8)){s.phase='fired';}return;}if(s.phase!=='play')return;if(s.dogIntro>0){s.dogIntro=Math.max(0,s.dogIntro-dt);if(s.dogIntro===0){s.event='bark';message(s,'RUN! BOOST + TRICKS · HAZARD PAY ACTIVE');}return;}s.comboTime=Math.max(0,s.comboTime-dt);if(s.comboTime===0&&!s.grindEnd){s.combo=0;s.comboKinds=[];}
 s.time-=dt;s.elapsed+=dt;s.toyCool=Math.max(0,s.toyCool-dt);s.dogDistract=Math.max(0,s.dogDistract-dt);
 if(s.stolen){s.stolen.remaining-=dt;s.stolen.at+=20*dt;if(Math.abs(s.distance-s.stolen.at)<22&&Math.abs(s.lane-s.dogLane)<.65){s.stolen=null;s.recovered++;s.chase=true;s.dogGap=8;s.job.at=Math.max(s.job.at,s.distance+200);message(s,'PACKAGE RECOVERED! BITEY IS NOT A COURIER.');s.event='deliver';}else if(s.stolen.remaining<=0){s.stolen=null;s.streak=0;s.time-=6;nextJob(s);s.chase=true;s.dogGap=10;message(s,'BITEY STOLE THE DELIVERY! −6 seconds');s.event='miss';}}
 if(s.routeEnd&&s.distance>=s.routeEnd){s.route='main';s.routeEnd=0;message(s,'BACK ON THE MAIN STREET');}
 s.forkOpen=!s.routeEnd&&s.distance>=s.forkAt-220;
 if(s.forkOpen&&(input.route==='safe'||input.route==='shortcut'||s.distance>=s.forkAt)){const picked=input.route||(s.targetLane===1?'shortcut':'safe');s.route=picked;s.routeEnd=s.distance+650;s.forkOpen=false;s.dogReadyAt=s.elapsed+2;s.forkAt=s.routeEnd+700;if(picked==='shortcut'){s.shortcuts++;if(s.job.at-s.distance>260)s.job.at-=100;}message(s,picked==='shortcut'?'SHORTCUT! +50% DELIVERY PAY · WATCH THE OBSTACLES':'SCENIC ROUTE · LESS TRAFFIC · TOP SPEED 31 MPH');s.event='grind';}input.route=null;
 if(input.toy){input.toySide=input.toy===-1?-1:1;input.toy=false;if(s.chase&&s.dogIntro===0&&s.toys>0&&s.toyCool===0&&s.dogDistract===0){s.toys--;s.toyCool=12;s.dogDistract=3;s.dogEscapeHold=0;s.effects.push({type:'toy',fromLane:s.lane,lane:input.toySide===-1?-1:1,started:s.elapsed,until:s.elapsed+3});message(s,'SQUEAK! BITEY IS DISTRACTED · 3 SECONDS');s.event='squeak';}else message(s,s.toys===0?'OUT OF SQUEAKY TOYS!':'Save the toy for an active chase.');}
 s.stun=Math.max(0,s.stun-dt);s.jumpCool=Math.max(0,s.jumpCool-dt);s.deliverCool=Math.max(0,s.deliverCool-dt);const wasAirborne=s.jump>0;s.jump=Math.max(0,s.jump-dt);s.landing=Math.max(0,s.landing-dt);if(wasAirborne&&s.jump===0)s.landing=.3;s.targetLane=clamp(s.targetLane+(input.right?1:0)-(input.left?1:0),-1,1);input.right=input.left=false;s.lane+=(s.targetLane-s.lane)*Math.min(1,dt*10);
 const desired=s.stun>0?10:input.brake?18:(input.boost||input.screenBoost)?(s.route==='safe'?50:60):30;s.speed+=(desired-s.speed)*dt*5;s.distance+=s.speed*dt;
 if(input.jump&&s.jumpCool===0&&s.stun===0)launch(s,random);
 if(s.grindEnd){s.comboTime=6;if(Math.abs(s.lane-s.grindLane)>.42||s.stun>0){s.grindEnd=0;message(s,'HOPPED OFF THE RAIL');}else if(s.distance>=s.grindEnd){s.cash+=10;s.grindEnd=0;s.landing=.3;message(s,'CLEAN GRIND FINISH! +$10');s.event='grind';}else{const earned=Math.floor((s.distance-s.grindPaid)/25);if(earned>0){s.cash+=earned*3;s.grindPaid+=earned*25;message(s,'GRINDING! +$'+earned*3);}}}
 if(s.distance>s.spawnAt){const roll=random(),district=neighborhood(s);let type=district===2?(roll<.18?'car':roll<.3?'barrel':roll<.75?'rail':'ramp'):district===1?(roll<.25?'car':roll<.65?'barrel':roll<.85?'rail':'ramp'):(roll<.38?'car':roll<.56?'barrel':roll<.78?'rail':'ramp');
 if(s.route==='safe')type=roll<.1?'car':roll<.3?'sprinkler':roll<.45?'pedestrian':roll<.65?'rail':'ramp';else if(s.route==='shortcut')type=roll<.2?'barrel':roll<.4?'pedestrian':roll<.55?'sprinkler':roll<.75?'car':roll<.9?'rail':'ramp';else if(roll>.38&&roll<.48)type='barrel';else if(roll>=.48&&roll<.52)type='sprinkler';else if(roll>=.52&&roll<.56)type='pedestrian';
 if(random()<.16)type='toy';s.spawnAt=s.distance+(s.route==='safe'?210:s.route==='shortcut'?90:type==='rail'?210:100)+random()*70;s.obstacles.push({z:s.distance+(s.route==='main'?680:380),lane:Math.floor(random()*3)-1,type,length:type==='rail'?(district===2?240:140):0,hit:false});}

 for(const o of s.obstacles){if(o.type==='pedestrian')o.lane=Math.sin(s.elapsed*.85+o.z*.01)*.95;const z=o.z-s.distance;
 if(o.type==='toy'){if(!o.hit&&z<14){o.hit=true;if(z> -15&&Math.abs(s.lane-o.lane)<.6){if(s.toys<3){s.toys++;message(s,'SQUEAKY TOY COLLECTED! Q ← / R →');s.event='squeak';}else message(s,'TOY BAG FULL · 3 / 3');}}continue;}
 // Rails remain catchable along their whole length, not just one frame at the front.
 if(o.type==='rail'){if(!o.hit&&!s.grindEnd&&s.stun===0&&(s.jump>0?z<=28:z<=14)&&z+(o.length||140)>8&&Math.abs(s.lane-o.lane)<.6){o.hit=true;s.cash+=10;link(s,'grind');s.grindEnd=o.z+(o.length||140);s.grindLane=o.lane;s.lane=s.targetLane=o.lane;s.grindPaid=s.distance;s.jump=0;s.jumpCool=0;if(s.chase)s.dogGap+=2;message(s,'RAIL GRIND! +$10 · STAY IN THIS LANE');s.event='grind';}continue;}
 if(!o.hit&&z<14){o.hit=true;const clearance=Math.abs(s.lane-o.lane);if(o.type==='car'&&z> -15&&clearance>=.48&&clearance<1.08&&s.jump===0){s.cash+=8;s.nearMisses++;message(s,'TOO CLOSE! NEAR MISS +$8');s.event='grind';}if(z> -15&&Math.abs(s.lane-o.lane)<.48){if(o.type==='ramp'){launch(s,random,true);}else if(o.type==='car'&&s.jumpHeight>100&&s.jump>0){s.lastDodge=s.elapsed;message(s,'CLEARED THE CAR! DELIVER WITHIN 3s FOR +$25');}else if(o.type==='car'||(s.jump===0&&!s.grindEnd)){if(['HOT SOUP','CACTUS CAKE'].includes(s.job.cargo)){s.condition=Math.max(.4,s.condition-.3);}s.stun=1.25;s.grindEnd=0;s.time-=3;s.crashes++;s.combo=0;s.comboTime=0;s.comboKinds=[];if(s.chase)s.dogGap-=5;message(s,(o.type==='sprinkler'?'SOAKED!':o.type==='door'?'DOOR WIPEOUT!':o.type==='pedestrian'?'PARCEL PILEUP!':'WIPEOUT!')+' −3 seconds');s.event='crash';if(o.type==='car'){s.endReason='car';s.phase='ambulance';s.ambulance=0;s.jump=0;s.grindEnd=0;s.event='siren';message(s,'CAR COLLISION! SHIFT OVER.');return;}}else if(s.jump>0){s.lastDodge=s.elapsed;message(s,'OBSTACLE CLEARED! SPECIAL DELIVERY WINDOW · 3s');}}}}s.obstacles=s.obstacles.filter(o=>o.z+(o.length||0)>s.distance-80);
 const remaining=s.job.at-s.distance;
 if(input.deliver&&s.stolen){message(s,'BITEY HAS YOUR PACKAGE! BOOST INTO HIS LANE TO RECOVER IT.');}
 if(input.deliver&&!s.stolen&&s.deliverCool===0){s.deliverCool=.4;if(remaining<160&&remaining> -95){const tossed=!(Math.abs(remaining)<95&&Math.abs(s.lane-s.job.side)<.58);let bonus=s.chase?50:0;const perfect=Math.abs(remaining)<40,late=remaining< -55,rating=perfect?'PERFECT TOSS!':late?'LATE CATCH!':'NICE DELIVERY!',tip=Math.round((perfect?15:late?0:5)*s.condition);const comboReward=s.comboTime>0&&s.comboKinds.length>=2?Math.min(60,s.comboKinds.length*10+s.combo*2):0;s.tips+=tip;s.comboBonus+=comboReward;link(s,'delivery');s.streak++;s.bestStreak=Math.max(s.bestStreak,s.streak);const streakTip=s.streak%3===0?25:0,specialTip=s.elapsed-s.lastDodge<=3?25:0,basePay=Math.round(s.job.pay*s.condition+1e-9);s.streakBonus+=streakTip;s.specialBonus+=specialTip;if(specialTip)s.lastDodge=-100;const routeTip=s.route==='shortcut'?Math.round(basePay*.5):0;s.routeBonus+=routeTip;s.cash+=basePay+bonus+tip+comboReward+routeTip+streakTip+specialTip;s.hazard+=bonus;s.jobs++;s.effects.push({type:tossed?'throw':'delivery',fromLane:s.lane,lane:s.job.side,targetZ:s.job.at,cargo:s.job.cargo,rating,tip,reaction:s.condition<1?(s.job.cargo==='HOT SOUP'?'WHERE IS THE REST OF MY SOUP?!':'MY CAKE HAS SEEN THINGS.'):perfect?'NOW THAT IS EXPRESS!':late?'I ORDERED THIS YESTERDAY!':'THANKS, SKATER!',started:s.elapsed,until:s.elapsed+(tossed?1.8:1.2)});message(s,rating+' +$'+(basePay+bonus+tip+comboReward+routeTip+streakTip+specialTip)+(comboReward?' · COMBO +$'+comboReward:'')+(bonus?' · HAZARD PAY!':'')+(routeTip?' · SHORTCUT +$'+routeTip:'')+(streakTip?' · STREAK +$25':'')+(specialTip?' · SPECIAL DELIVERY +$25':'')+(s.condition<1?' · DAMAGED CARGO':''));s.event='deliver';s.time=Math.min(75,s.time+6);nextJob(s);}else message(s,'Get within 160 m to throw. Press E / Throw.');}
 if(!s.stolen&&remaining< -100){s.time-=6;s.streak=0;s.combo=0;s.comboTime=0;s.comboKinds=[];message(s,'MISSED DELIVERY! −6 seconds');s.event='miss';nextJob(s);}
 if(!s.stolen&&!s.forkOpen&&s.elapsed>=s.dogReadyAt&&(s.routeEnd||s.distance<s.forkAt-240)&&((s.dogEvents===0&&s.elapsed>14)||(s.dogEvents===1&&s.elapsed>48))){s.dogStole=false;s.dogEvents++;s.dogIntro=s.dogEvents===1?5.2:0;s.chase=true;s.dogGap=10;s.dogEscapeHold=0;s.dogLane=clamp(s.lane+(s.lane<=0?.8:-.8),-1,1);s.dogTurn=0;message(s,'LOOK OUT! MR. BITEY WANTS YOUR JOB!');s.event=s.dogEvents===1?'doom':'bark';}
 if(s.chase&&s.dogIntro===0){if(s.dogDistract>0){const toy=s.effects.find(e=>e.type==='toy');s.dogTurn=(toy?.lane||1)-s.dogLane;s.dogLane+=s.dogTurn*Math.min(1,dt*3);s.dogEscapeHold=0;}else{s.dogTurn=s.lane-s.dogLane;s.dogLane+=s.dogTurn*Math.min(1,dt*2.6);s.dogGap+=(s.speed-34)*dt*.18;s.dogEscapeHold=s.dogGap>=24?s.dogEscapeHold+dt:0;s.dogGap=Math.min(25,s.dogGap);if(s.dogEscapeHold>=3){s.chase=false;s.cash+=15;message(s,'DOG DITCHED! +$15 survival bonus');s.event='escape';}if(!s.dogStole&&s.dogGap>0&&s.dogGap<3&&Math.abs(s.lane-s.dogLane)<.4){s.dogStole=true;s.thefts++;s.stolen={at:s.distance+100,remaining:7,cargo:s.job.cargo};s.chase=false;message(s,'BITEY STOLE YOUR PACKAGE! BOOST AFTER HIM · 7 SECONDS');s.event='bark';}if(s.dogGap<=0&&Math.abs(s.lane-s.dogLane)<.35){s.endReason='dog';s.phase='ambulance';s.ambulance=0;s.jump=0;s.grindEnd=0;s.event='siren';message(s,'THIS SHIFT HAS TAKEN A TURN.');}}}
 if(s.time<=0&&s.phase==='play'){s.time=0;s.phase='complete';s.event='complete';}
}
