export class Multiplayer {
 constructor(onState){this.onState=onState;this.room=null;this.token=null;this.seq=0;this.pending={};this.busy=false;this.last=0;this.error='';this.laneInputs=[];this.jumpSeq=0;}
 async call(action,extra={}){const r=await fetch('/api/race',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,code:this.room?.code,token:this.token,...extra})});const data=await r.json();if(!r.ok)throw Error(data.error||'Connection lost');if(data.token)this.token=data.token;this.room=data.room;const mine=this.room?.players.find(p=>p.id===this.room.you);if(mine?.seq!==undefined)this.laneInputs=this.laneInputs.filter(i=>i.seq>mine.seq);this.error='';this.onState(this.room);return data;}
 async enter(action,name,code){await this.call(action,{name,code});this.seq=0;this.laneInputs=[];this.jumpSeq=0;}
 collect(keys){for(const direction of [-1,1]){const k=direction<0?'left':'right';if(keys[k]){(this.pending.laneSteps||=[]).push(direction);this.laneInputs.push({seq:this.seq+1,direction});keys[k]=false;}}if(keys.jump)this.jumpSeq=this.seq+1;for(const k of ['jump','deliver']){if(keys[k]){this.pending[k]=true;keys[k]=false;}}if(keys.toyLeft||keys.toyRight){this.pending.toy=keys.toyLeft?-1:1;keys.toyLeft=keys.toyRight=false;}}
 tick(now,keys){if(!this.room||this.busy||now-this.last<160)return;this.last=now;this.busy=true;const batch=this.pending;this.pending={};const input={...batch,boost:!!(keys.boost||keys.screenBoost),brake:!!keys.brake};this.call(this.room.phase==='race'?'input':'poll',{seq:++this.seq,input}).catch(e=>{this.error=e.message;if(batch.laneSteps)this.pending.laneSteps=[...batch.laneSteps,...(this.pending.laneSteps||[])];for(const k of ['jump','deliver','toy'])if(batch[k])this.pending[k]=batch[k];}).finally(()=>this.busy=false);}
 predictedLane(target){for(const i of this.laneInputs)target=Math.max(-1,Math.min(1,target+i.direction));return target;}
 async leave(){const r=this.room;try{await this.call('leave');}catch{}this.room=null;this.token=null;this.pending={};this.onState(null);}
}
