import assert from 'node:assert/strict';import {createShift,update,JOBS} from './dist/engine.js';import {mutate,advance} from './server/rooms.js';
function shift(index){const s=createShift(index);s.obstacles=[];s.forkAt=s.spawnAt=s.dogReadyAt=Infinity;return s;}
function deliver(index,age,condition=1){const s=shift(index);s.elapsed=age;s.condition=condition;s.distance=s.job.at;s.lane=s.targetLane=s.job.side;update(s,{deliver:true},.01,()=>.9);return s;}
let hot=deliver(5,10),cold=deliver(5,28);assert.ok(hot.cash>cold.cash);assert.equal(cold.cargoBonus,0);assert.equal(hot.cargoBonus,7);
let trophy=shift(6);trophy.obstacles=[{z:1,lane:0,type:'barrel',hit:false}];update(trophy,{},.01,()=>.9);assert.equal(trophy.condition,.55);assert.ok(deliver(6,10).cash>deliver(6,10,.55).cash);assert.equal(deliver(6,10).cargoBonus,8);
let cake=shift(8);cake.speed=60;cake.jump=.005;update(cake,{},.01,()=>.9);assert.equal(cake.condition,.88);let gentle=shift(8);gentle.jump=.005;update(gentle,{},.01,()=>.9);assert.equal(gentle.condition,1);assert.equal(deliver(8,10).cargoBonus,8);
let lobster=shift(7);lobster.elapsed=8;update(lobster,{},.01,()=>.9);assert.ok(lobster.lobsterWarning>0);update(lobster,{secure:true},.01,()=>.9);assert.equal(lobster.lobsterWarning,0);assert.equal(lobster.cargoSaves,1);lobster.distance=lobster.job.at;lobster.lane=lobster.targetLane=-1;update(lobster,{deliver:true},.01,()=>.9);assert.equal(lobster.cargoBonus,5);assert.equal(lobster.cargoSaves,0);
lobster=shift(7);lobster.elapsed=8;for(let i=0;i<310;i++)update(lobster,{},.01,()=>.9);assert.notEqual(lobster.job.cargo,'LIVE LOBSTER');assert.ok(lobster.effects.some(e=>e.type==='lobsterEscape'));
const p={id:'a',token:'t',seen:1000,input:{},seq:0,rng:1,game:shift(7)};p.game.lobsterWarning=2;const room={phase:'race',starts:1000,tick:1000,players:[p]};mutate(room,{action:'input',token:'t',seq:1,input:{secure:true}},1000);advance(room,1050);assert.equal(p.game.lobsterWarning,0);assert.equal(p.game.cargoSaves,1);assert.equal(JOBS.length,9);console.log('PASS hot pizza tips, fragile trophy damage/pay, cake landing protection, lobster warning/secure/escape/reward reset and authoritative secure input.');
